# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Portable-Windows-Apps.KeePass
PackageVersion: "2.54"
PackageLocale: en-US
Publisher: Portable Apps For Windows
PackageName: Portable-KeePass-2.54
License: GNU GENERAL PUBLIC LICENSE
ShortDescription: Portable version of KeePass 2.54
ManifestType: defaultLocale
ManifestVersion: 1.6.0
